plugins:
  chat_integration_enabled:
    default: false
  chat_integration_discourse_username:
    default: system
  chat_integration_delay_seconds:
    default: 20

#######################################
########## SLACK SETTINGS #############
#######################################
  chat_integration_slack_enabled:
    default: false
  chat_integration_slack_outbound_webhook_url:
    default: ''
  chat_integration_slack_discourse_excerpt_length:
    default: 400
  chat_integration_slack_icon_url:
    default: ''
  chat_integration_slack_access_token:
    default: ''

#######################################
######### TELEGRAM SETTINGS ###########
#######################################
  chat_integration_telegram_enabled:
    default: false
